development:
  adapter: postgresql
  encoding: utf8
  database: rantly_development
  pool: 5
  username: 
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: rantly_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: rantly_production
  pool: 5
  username: 
  password:
